-- Table: DW.dw_facebook_post_insights

-- DROP TABLE IF EXISTS DW.dw_facebook_post_insights;
CREATE TABLE IF NOT EXISTS "DW".dw_facebook_post_insights
(
    insights_created_date date,
    post_activity bigint,
    post_activity_by_action_type json[],
    post_activity_by_action_type_unique json[],
    post_activity_unique bigint[],
    post_clicks bigint[],
    post_clicks_by_type json[],
    post_clicks_by_type_unique json[],
    post_clicks_unique bigint[],
    post_engaged_fan bigint[],
    post_engaged_users bigint[],
    post_id bigint NOT NULL,
    post_impressions bigint,
    post_impressions_by_story_type json,
    post_impressions_by_story_type_unique json[],
    post_impressions_fan bigint[],
    post_impressions_fan_paid bigint[],
    post_impressions_fan_paid_unique bigint[],
    post_impressions_fan_unique bigint[],
    post_impressions_nonviral bigint[],
    post_impressions_nonviral_unique bigint[],
    post_impressions_organic bigint[],
    post_impressions_organic_unique bigint[],
    post_impressions_paid bigint[],
    post_impressions_paid_unique bigint[],
    post_impressions_unique bigint[],
    post_impressions_viral bigint[],
    post_impressions_viral_unique bigint[],
    post_negative_feedback bigint,
    post_negative_feedback_by_type json[],
    post_negative_feedback_by_type_unique json[],
    post_negative_feedback_unique bigint,
    post_reactions_anger_total bigint[],
    post_reactions_by_type_total json[],
    post_reactions_haha_total bigint[],
    post_reactions_like_total bigint[],
    post_reactions_love_total bigint[],
    post_reactions_sorry_total bigint,
    post_reactions_wow_total bigint[],
    post_video_avg_time_watched bigint[],
    post_video_complete_views_organic bigint[],
    post_video_complete_views_organic_unique bigint[],
    post_video_complete_views_paid bigint[],
    post_video_complete_views_paid_unique bigint[],
    post_video_length bigint[],
    post_video_retention_graph json[],
    post_video_retention_graph_autoplayed json[],
    post_video_retention_graph_clicked_to_play json[],
    post_video_view_time bigint[],
    post_video_view_time_by_age_bucket_and_gender json[],
    post_video_view_time_by_country_id json[],
    post_video_view_time_by_distribution_type json[],
    post_video_view_time_by_region_id json[],
    post_video_view_time_organic bigint[],
    post_video_views bigint[],
    post_video_views_10s bigint[],
    post_video_views_10s_autoplayed bigint[],
    post_video_views_10s_clicked_to_play bigint[],
    post_video_views_10s_organic bigint[],
    post_video_views_10s_paid bigint[],
    post_video_views_10s_sound_on bigint[],
    post_video_views_10s_unique bigint[],
    post_video_views_autoplayed bigint[],
    post_video_views_by_distribution_type json[],
    post_video_views_clicked_to_play bigint[],
    post_video_views_organic bigint[],
    post_video_views_organic_unique bigint[],
    post_video_views_paid bigint[],
    post_video_views_paid_unique bigint[],
    post_video_views_sound_on bigint[],
    post_video_views_unique bigint[],
    period text[] COLLATE pg_catalog."default",
	 CONSTRAINT dw_facebook_post_insights_pkey PRIMARY KEY (post_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "DW".dw_facebook_post_insights
    OWNER to postgres;